# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MDFEU0vFAPE0tfW_E7MzFVSm2x4tAESu
"""

import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="🌾 Smart AgriTwin - Indian Agriculture", page_icon="🌱", layout="wide")

# Background image CSS
st.markdown("""
<style>
.stApp {background-image: url('https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1400&q=80');
        background-size: cover;}
</style>
""", unsafe_allow_html=True)

def login_page():
    st.markdown("<h1 style='color:#40631e;text-align:center'>🌾 SMART AGRI TWIN</h1>", unsafe_allow_html=True)
    st.markdown("<h3 style='text-align:center; color:#2e8b57;'>Optimizing Crop Yield and Market Access for Indian Farmers</h3>", unsafe_allow_html=True)
    st.image("https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=800&q=80", use_column_width=True)
    st.markdown("""
    <div style='background:rgba(255,255,255,0.8);padding:16px;border-radius:10px;'>
    <b>Welcome! This dashboard helps Indian farmers and researchers boost crop yields and market profits using local soil and production data.<br>
    Enter your details below to get started:</b> </div>
    """, unsafe_allow_html=True)
    with st.form("login"):
        name = st.text_input("Your name")
        role = st.selectbox("Who are you?", ["Farmer", "Student", "Researcher", "Other"])
        purpose = st.text_area("Your purpose (crop selection, soil health, market info, etc.)")
        submitted = st.form_submit_button("Enter Dashboard")
    if submitted and name:
        st.session_state.update({"auth": True, "name": name, "role": role, "purpose": purpose})

if "auth" not in st.session_state:
    st.session_state["auth"] = False

if not st.session_state["auth"]:
    login_page()
    st.stop()
else:
    # Personalized greeting & purpose explanation
    st.success(f"Hello {st.session_state['name']} ({st.session_state['role']})! Purpose: {st.session_state['purpose']}.")
    st.markdown("**This dashboard will help you:**")
    st.markdown("- Identify the best crops for your region based on data")
    st.markdown("- Manage and improve soil health")
    st.markdown("- Track crop performance and market options")
    st.write("---")

    # Load Data
    @st.cache_data
    def load():
        crop = pd.read_csv('icrisat_long_cleaned.csv')
        soil = pd.read_csv('Soil-data-cleaned.csv')
        return crop, soil
    crop, soil = load()

    # Land/crop suitability (example: "top district/crop for wheat/maize")
    st.header("🌿 Crop Recommendations by District")
    if 'Nitrogen' in soil.columns and 'District' in soil.columns and 'Crop' in crop.columns:
        merged = pd.merge(crop, soil, on='District')
        top_crops = merged.groupby(['District','Crop'])['Nitrogen'].mean().reset_index()
        best = top_crops.sort_values('Nitrogen', ascending=False).groupby('District').first().reset_index()
        st.table(best[['District','Crop','Nitrogen']].rename(columns={'Crop':'Recommended Crop','Nitrogen':'Avg. Soil N'}))
        st.markdown("> _Focus interventions on low-nitrogen areas; choose high-nitrogen for yield-intensive crops._")
    st.write("---")

    # Tabs for all insights/visualizations
    tabs = st.tabs([
        "Total Wheat by District", "Wheat Over Years",
        "Main Crop by District", "Soil pH", "Soil Nitrogen", "Soil Correlation"
    ])
    # Visualization 1
    with tabs[0]:
        st.subheader("🌾 Total Wheat Production by District")
        wheat = crop[crop['Crop'].str.lower() == "wheat"]
        dist_data = wheat.groupby('District')['Production'].sum().reset_index()
        fig = px.bar(dist_data, x='District', y='Production', color='Production',
                     color_continuous_scale='YlGn', title="Wheat Production by District")
        st.plotly_chart(fig, use_container_width=True)
        st.markdown("**Insight:** Some districts produce much more wheat—learn from high-yielding zones.")

    # ...Repeat for other insights in other tabs, using similar color and professional layout...

    # Recommendation Summary
    st.header("Summary & Guidance")
    st.markdown("- Follow best practices from high-performing districts")
    st.markdown("- Correct low soil pH/nitrogen with local amendments")
    st.markdown("- Match crop choice to local soil features")
    st.markdown("- Use this dashboard regularly for trend monitoring and resource planning")
    st.image("https://cdn.pixabay.com/photo/2015/09/09/19/34/agriculture-933167_1280.jpg", caption="Indian Farmers - The Heart of Our Nation", use_column_width=True)

