# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MDFEU0vFAPE0tfW_E7MzFVSm2x4tAESu
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile streamlit_app.py
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# 
# # Load data
# def load_data():
#     soil = pd.read_csv('Soil-data-cleaned.csv')
#     crop = pd.read_csv('icrisat_long_cleaned.csv')
#     return soil, crop
# 
# soil, crop = load_data()
# 
# st.title('Smart AgriTwin Dashboard')
# 
# # Sidebar filters
# crop_names = crop['Crop'].unique()
# selected_crop = st.sidebar.selectbox('Select Crop', crop_names)
# 
# filtered_crop = crop[crop['Crop'] == selected_crop]
# 
# st.subheader(f'{selected_crop} Production Over Years')
# yearly_prod = filtered_crop.groupby('Year')['Production'].sum().reset_index()
# fig1 = px.line(yearly_prod, x='Year', y='Production')
# st.plotly_chart(fig1)
# 
# st.subheader(f'{selected_crop} Production by District')
# district_prod = filtered_crop.groupby('District')['Production'].sum().reset_index()
# fig2 = px.bar(district_prod, x='District', y='Production')
# st.plotly_chart(fig2)
# 
# st.subheader('Soil Nitrogen Distribution')
# st.bar_chart(soil['Nitrogen'])
#

from pyngrok import ngrok
ngrok.set_auth_token('33ax01Eye4XYeGTWFeQXnJJWgpF_2KEk2CU6dPAT1p7xssGRh')

!streamlit run streamlit_app.py &

public_url = ngrok.connect(port='8501')
print(f'Dashboard URL: {public_url}')